# Generated by Django 3.1.4 on 2021-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_head', models.CharField(max_length=30)),
                ('task_dres', models.TextField()),
            ],
        ),
    ]
